<?php

use App\Models\SpecialistType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialistsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SpecialistType::insert($this->specialists);
    }

    private $specialists = [
        ["name" => "Colon and rectal surgery"],
        ["name" => "Gynecologic oncology"],
        ["name" => "Plastic surgery"],
        ["name" => "Neurological surgery"],
        ["name" => "Ophthalmic surgery"],
        ["name" => "Orthopaedic surgery"],
        ["name" => "Foot and ankle orthopaedics"],
        ["name" => "Musculoskeletal oncology"],
        ["name" => "Orthopaedic sports medicine"],
        ["name" => "Orthopaedic surgery of the spine "],
        ["name" => "Orthopaedic trauma"],
        ["name" => "Pediatric orthopaedics"],
        ["name" => "Otolaryngology"],
        ["name" => "Pediatric otolaryngology"],
        ["name" => "Otology neurotology"],
        ["name" => "Pediatric surgery"],
        ["name" => "Neonatal"],
        ["name" => "Prenatal"],
        ["name" => "Trauma"],
        ["name" => "Pediatric oncology"],
        ["name" => "Thoracic Surgery"],
//        ["name" => "Congenital cardiac surgery"],
//        ["name" => "Thoracic surgery-integrated"],
//        ["name" => "Psychosomatic medicine"],
//        ["name" => "Child and adolescent psychiatry"],
//        ["name" => "Addiction psychiatry"],
//        ["name" => "Forensic psychiatry"],
//        ["name" => "Aerospace medicine"],
//        ["name" => "Medical toxicology"],
//        ["name" => "Occupational medicine"],
//        ["name" => "Brain injury medicine"],
//        ["name" => "Hospice and palliative medicine"],
//        ["name" => "Neuromuscular medicine"],
//        ["name" => "Pain medicine"],
//        ["name" => "Pediatric rehabilitation medicine"],
//        ["name" => "Spinal cord injury medicine"],
//        ["name" => "Sports medicinePublic health medicine"],
//        ["name" => "Child abuse pediatrics"],
//        ["name" => "Developmental-behavioral pediatrics"],
//        ["name" => "Neonatal-perinatal medicine"],
//        ["name" => "Pediatric cardiology"],
//        ["name" => "Pediatric critical care medicine"],
//        ["name" => "Anatomical pathology"],
//        ["name" => "Blood banking and transfusion medicine"],
//        ["name" => "Chemical pathology"],
//        ["name" => "Clinical pathology"],
//        ["name" => "Cytopathology"],
//        ["name" => "Forensic pathology"],
//        ["name" => "Genetic pathology"],
//        ["name" => "Hematology"],
//        ["name" => "Anterior segment/cornea ophthalmology"],
//        ["name" => "Glaucoma ophthalmology"],
//        ["name" => "Neuro-ophthalmology"],
//        ["name" => "Ocular oncology"],
//        ["name" => "Oculoplastics/orbit"],
//        ["name" => "Ophthalmic Plastic & Reconstructive Surgery"],
//        ["name" => "Female pelvic medicine and reconstructive surgery "],
//        ["name" => "Gynecologic oncology"],
//        ["name" => "Maternal-fetal medicine"],
//        ["name" => "Reproductive endocrinologists and infertility"],
//        ["name" => "Brain injury medicine"],
//        ["name" => "Child neurology"],
//        ["name" => "Clinical neurophysiology"],
//        ["name" => "Endovascular surgical neuroradiology"],
//        ["name" => "Hospice and palliative medicine"],
//        ["name" => "Neurodevelopmental disabilities"],
//        ["name" => "Neuromuscular medicine"],
//        ["name" => "Pain medicine"],
//        ["name" => "Sleep medicine"],
//        ["name" => "Biochemical genetics"],
//        ["name" => "Clinical cytogenetics"],
//        ["name" => "Clinical genetics"],
//        ["name" => "Molecular genetic patholo"],
//        ["name" => "Advanced heart failure and transplant cardiology"],
//        ["name" => "Cardiovascular disease"],
//        ["name" => "Clinical cardiac electrophysiology"],
//        ["name" => "Critical care medicine"],
//        ["name" => "Endocrinology, diabetes, and metabolism"],
//        ["name" => "Gastroenterology"],
//        ["name" => "Geriatric medicine"],
//        ["name" => "Hematology"],
//        ["name" => "Hematology and oncology"],
//        ["name" => "Infectious disease"],
//        ["name" => "Internal medicine"],
//        ["name" => "Interventional cardiology"],
//        ["name" => "Nephrology"],
//        ["name" => "Oncology"],
//        ["name" => "Pediatric internal medicine"],
//        ["name" => "Pulmonary disease"],
//        ["name" => "Pulmonary disease and critical care medicine"],
//        ["name" => "Rheumatology"],
//        ["name" => "Sleep medicine"],
//        ["name" => "Sports medicine"],
//        ["name" => "Transplant hepatology"],
//        ["name" => "Adolescent medicine"],
//        ["name" => "Geriatric medicine"],
//        ["name" => "Hospice and palliative medicine"],
//        ["name" => "Pain medicine"],
//        ["name" => "Sleep medicine"],
//        ["name" => "Sports medicine"],
//        ["name" => "Anesthesiology critical care medicine"],
//        ["name" => "Emergency medical services"],
//        ["name" => "Hospice and palliative medicine "],
//        ["name" => "Internal medicine / Critical care medicine"],
//        ["name" => "Medical toxicology"],
//        ["name" => "Pain medicine"],
//        ["name" => "Pediatric emergency medicine "],
//        ["name" => "Sports medicine "],
//        ["name" => "Endovascular surgical neuroradiology"],
//        ["name" => "Gastrointestinal radiology"],
//        ["name" => "Genitourinary radiology"],
//        ["name" => "Head and neck radiology"],
//        ["name" => "Interventional radiology"],
//        ["name" => "Musculoskeletal radiology"],
//        ["name" => "Neuroradiology"],
//        ["name" => "Nuclear radiology"],
//        ["name" => "Cardiothoracic radiology"],
//        ["name" => "ALLERGY & IMMUNOLOGY"]
    ];
}
